add missing icon
aodn/nrmn-application pull request #1015
Opened 2022-05-17 07:01 UTC by utas-raymondng

2022-05-17 23:34 UTC, nspool requested changes
Please also match the gray colour for the grid icon, and also the spacing in the original screenshot. I think the grid might need to be in it's own column, and the row height increased.

2022-05-18 01:08 UTC, utas-raymondng commented
> Please also match the gray colour for the grid icon, and also the spacing in the original screenshot. I think the grid might need to be in it's own column, and the row height increased.

Updated as per comments

2022-05-18 01:18 UTC, nspool approved these changes

2022-05-18 01:18 UTC, nspool commented on web/src/components/job/JobList.js
> +            cellRenderer={(e) => (e.data?.status === 'STAGED' ? <GridOn htmlColor={'#808080'} viewBox={iconViewBoxDimension}/> : <></>)}
Try and avoid inline styling like this.

2022-05-18 01:18 UTC, nspool commented on web/src/components/job/JobList.js
> +  const iconViewBoxDimension = '-2 -2 30 30';
Try to avoid using transforms, especially for elements in grids where there are many rows.

2022-05-18 01:18 UTC, merged