Feature/validation job UI
aodn/nrmn-application pull request #110
Opened 2021-01-13 04:09 UTC by utas-tajona

2021-01-13 04:39 UTC, pmbohm requested changes
This pull request is a grab bag of many changes, that if merged will break many considered advancements unrelated to 'Validation jobs'

- Addition of linting should be left out until the start of an iteration. Create a pull request with no code changes just linting added
- Removal of node-sass left out until this can be separately demonstrated to be beneficial
- Refactoring of code not related to 'Validation job' in a separate pull request

2021-01-13 04:43 UTC, utas-tajona commented
@pmbohm  linting is just a file config and part of the build. once merge with master all the project is eslint valid.
- sass is gone,  this branch is a solid example how good material  theme works (grouping, pivot ....)

2021-01-14 22:32 UTC, utas-tajona commented
https://github.com/aodn/backlog/issues/2533

2021-01-17 22:58 UTC, utas-tajona commented
The two PRs have been merged. this PR is down to 48 files now it should be ready for review

2021-01-18 01:22 UTC, pmbohm reviewed
There is still a lot of lint changes clouding this pull request, and there are still parts that should be separated out, so that the guts of the 'validation job' uploads can be considered

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/import/ColumnDef.js
> +        width: 75
What about using a variable for these?

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/import/middleware/create-import.js
> +        console.log(payload);
console.logs

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/import/reducers/create-import.js
> +                console.log(errorsGrouped);
console.debug instead?

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/import/reducers/create-import.js
> +                console.log(state.errorsByMsg);
console.debug instead?

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/layout/AuthState.js
>  import React from 'react';
This has nothing to do with validation jobs.
Additionally removing the ability to login or logout at any time has no purpose

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/layout/SideMenu.js
What is the purpose of this file change and its relation to validation jobs?

2021-01-18 01:22 UTC, pmbohm commented on ui/src/components/layout/TopBar.js
>  import Toolbar from '@material-ui/core/Toolbar';
This looks unrelated to validation jobs?

2021-01-18 03:31 UTC, utas-tajona commented on ui/.eslintrc.json
> +{
it's in my previous PR but i put in SRC by mistque, once the other PR approve it will be gone

2021-01-18 03:33 UTC, utas-tajona commented on ui/package.json
> -    "node-sass": "^4.14.1",
if you run the branch you can have a look at all AG-grid instance are working as intended.

2021-01-18 03:33 UTC, utas-tajona commented on ui/package.json
> -    "node-sass": "^4.14.1",
grouping, sorting, pivot

2021-01-18 03:34 UTC, utas-tajona commented on ui/src/components/data-entities/customWidgetFields/ArrayApiField.js
> +import React from 'react';
ok to be deleted

2021-01-18 03:35 UTC, pmbohm commented
Errors exist as an array with one element on load
<img width="609" alt="Screen Shot 2021-01-18 at 2 33 37 pm" src="https://user-images.githubusercontent.com/1066981/104869517-5a509c00-599a-11eb-807a-8b21a83a1a31.png">

2021-01-18 03:43 UTC, pmbohm commented
I'm getting errors on upload correctShortHeader.xlsx

http 422 Unprocessable Entity

Server side message
```
2021-01-18 14:36:23.143 ERROR 88998 --- [nio-8080-exec-5] a.o.a.n.r.service.SpreadSheetService     : Error while reading the excelFile:No valid entries or contents found, this is not a valid OOXML (Office Open XML) file
```

2021-01-20 04:15 UTC, utas-tajona commented on ui/.eslintrc.json
> +{
once #119  is merged this file will go away

2021-01-20 04:36 UTC, utas-tajona commented on ui/src/components/data-entities/customWidgetFields/ArrayApiField.js
> +import React from 'react';
gone

2021-01-20 05:06 UTC, utas-tajona commented
422 is beacuse your database is not update to date you have to change the dll-auto to update in spring

I have fixed the error  display, a check was missing in based form when the error is defined but empty.

2021-01-21 02:54 UTC, utas-tajona commented
I have also found a missing configuration that was removing the api payload in Axios now the upload display the correct error message

2021-01-25 01:17 UTC, merged