github action: use dockerfile instead of actions for build
aodn/nrmn-application pull request #1268
Opened 2023-03-29 01:06 UTC by nspool

2023-03-29 23:35 UTC, digorgonzola requested changes

2023-03-29 23:35 UTC, digorgonzola commented on .github/workflows/maven.yml
> -  cancel-in-progress: true
Don't we want to keep this?

2023-03-29 23:39 UTC, nspool commented on .github/workflows/maven.yml
> -  cancel-in-progress: true
Yes we do 😬
I'll add it back.

2023-03-30 00:00 UTC, digorgonzola approved these changes

2023-03-30 00:02 UTC, merged