EntityList row selection goes to details view
aodn/nrmn-application pull request #140
Opened 2021-02-11 01:08 UTC by pmbohm

2021-02-11 01:08 UTC, pmbohm commented
https://github.com/aodn/backlog/issues/2635

2021-02-12 02:17 UTC, utas-tajona requested changes

2021-02-12 02:17 UTC, utas-tajona commented on ui/src/components/data-entities/EntityList.js
> +  }
window.location need to be avoid. use the hook location instead

2021-02-12 02:17 UTC, utas-tajona commented on ui/src/components/data-entities/EntityList.js
> +  }
```
const history = useHistory();
.....

history.push('/view/' +ent + '/' + id);
```

2021-02-16 01:58 UTC, ccmoloney commented
@utas-tajona Can you please merge this if you are happy with the updates?

2021-02-16 03:23 UTC, merged