White screen after validation fix
aodn/nrmn-application pull request #154
Opened 2021-02-16 04:42 UTC by utas-tajona

2021-02-16 04:53 UTC, nspool requested changes
Looks good. Just needs some extra lines removed.

2021-02-16 04:53 UTC, nspool commented on ui/src/components/import/DataSheetView.js
> +  // var rows = immutableRows.map(Object.unfreeze);
Better to remove than comment out I think.

2021-02-16 04:53 UTC, nspool commented on ui/src/components/import/DataSheetView.js
> +            //  rowData={rows}
can be removed.

2021-02-16 04:53 UTC, nspool commented on ui/src/components/import/middleware/create-import.js
> +    console.debug('errors', errors);
Should remove these debug statements.

2021-02-17 00:35 UTC, jonescc reviewed
Have tested this out locally and validation looks to work better now (no white page), can copy/paste and depth has been added to pivotting

2021-02-17 00:35 UTC, jonescc commented
@nspool?

2021-02-17 00:39 UTC, nspool approved these changes

2021-02-17 00:39 UTC, merged