fixing submit button
aodn/nrmn-application pull request #229
Opened 2021-04-16 02:18 UTC by utas-tajona

2021-04-16 02:31 UTC, utas-tajona commented
https://github.com/aodn/backlog/issues/2890

2021-04-16 03:02 UTC, jonescc requested changes
I get 'Request method 'POST' not supported' when trying to submit - needs those changes you made in the other PR that's being held up by the ui_species_attributes view?

2021-04-16 03:05 UTC, nspool approved these changes

2021-04-16 03:05 UTC, nspool commented on ui/src/components/import/reducers/create-import.js
> +        state.enableSubmit = validationErrors.filter((err) => err.errorLevel === 'BLOCKING').length === 0;
minor style point: can use `some` instead of `filter`

2021-04-16 03:09 UTC, jonescc commented
> I get 'WARN 85224 --- [nio-8080-exec-3] o.s.web.servlet.PageNotFound Request method 'POST' not supported' when trying to submit

Might be related to the fact that this branch is behind master quite a bit now.  This ones based on 0.1.41 whereas edge is now 0.156  - perhaps merge in latest changes

2021-04-16 05:08 UTC, jonescc commented
Submitting returns 'Job with given id has not been validated: 11' even though I just validated the job and no errors were returned.

2021-04-19 05:42 UTC, ccmoloney commented
> Submitting returns 'Job with given id has not been validated: 11' even though I just validated the job and no errors were returned.

Is this still an issue @utas-tajona ?

2021-04-20 02:55 UTC, nspool commented
@utas-tajona when this is ready for review again could you please run up a stack as well?

2021-04-21 22:03 UTC, nspool commented
Testing against the `nrmn_dev` database is giving this error on sheet upload:
`Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into nrmn.staged_job (created, sec_user_id, is_extended_size, last_updated, program_id, reference, source, status, survey_ids, id) values ('2021-04-21 21:51:06.86+00', 123456, 'FALSE', '2021-04-21 21:51:06.86+00', 2, 'testfile4UIMaria2019.xlsx', 'INGEST', 'PENDING', NULL, 2) was aborted: ERROR: column "survey_ids" of relation "staged_job" does not exist`

2021-04-21 22:33 UTC, nspool commented
After adding the `survey_ids` column, noticing that Validate needs to be pressed twice after an edit for it to have an effect. Not sure if this is a new issue or a regression.

2021-04-21 22:34 UTC, utas-tajona commented
You can run  with ddl_auto=update or you can use edge db.
________________________________
From: nspool ***@***.***>
Sent: Thursday, April 22, 2021 8:03:21 AM
To: aodn/nrmn-application ***@***.***>
Cc: Tanjona Rafidison ***@***.***>; Mention ***@***.***>
Subject: Re: [aodn/nrmn-application] fixing submit button (#229)


Testing against the nrmn_dev database is giving this error on sheet upload:
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into nrmn.staged_job (created, sec_user_id, is_extended_size, last_updated, program_id, reference, source, status, survey_ids, id) values ('2021-04-21 21:51:06.86+00', 123456, 'FALSE', '2021-04-21 21:51:06.86+00', 2, 'testfile4UIMaria2019.xlsx', 'INGEST', 'PENDING', NULL, 2) was aborted: ERROR: column "survey_ids" of relation "staged_job" does not exist

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/aodn/nrmn-application/pull/229#issuecomment-824387336>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQD23XDWASVMBO22GU7TVB3TJ5DSTANCNFSM43ATQAPQ>.


This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

2021-04-21 23:03 UTC, nspool commented
Also running into an Internal Server Error. Getting the same error even when no sheets are staged and with a new sheet:

    org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "survey_method_unique"
    Detail: Key (survey_id, method_id, block_num)=(923400005, 3, 1) already exists.

2021-04-21 23:09 UTC, utas-tajona commented
Yes this is expected since we have missing validation related to methods and block

________________________________
From: nspool ***@***.***>
Sent: Thursday, April 22, 2021 9:04:10 AM
To: aodn/nrmn-application ***@***.***>
Cc: Tanjona Rafidison ***@***.***>; Mention ***@***.***>
Subject: Re: [aodn/nrmn-application] fixing submit button (#229)


Also running into an Internal Server Error. Getting the same error even when no sheets are staged and with a new sheet:

org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "survey_method_unique"
Detail: Key (survey_id, method_id, block_num)=(923400005, 3, 1) already exists.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/aodn/nrmn-application/pull/229#issuecomment-824419822>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQD23XARB5ISSR6W5DRYUQDTJ5KWVANCNFSM43ATQAPQ>.


This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

2021-04-21 23:33 UTC, nspool commented
Thanks, changing the date value fixes the constraint error. However am now getting a different internal server error:

    org.postgresql.util.PSQLException: ERROR: null value in column "observable_item_id" violates not-null constraint
    Detail: Failing row contains (2284994, 140047, 186, null, 52, 1, null).

Also these errors are not being displayed in the warning. The only thing showing in the webapp is "Internal Server Error".

2021-04-21 23:54 UTC, nspool commented
Complete server log for `observable_item_id` submission error:
[backtrace.txt](https://github.com/aodn/nrmn-application/files/6354509/backtrace.txt)

2021-04-22 00:57 UTC, utas-tajona commented
from the backtrace it seems to be the same error:   Detail: Key (survey_id, method_id, block_num)=(923400006, 2, 2) already exists.

2021-04-22 01:26 UTC, utas-tajona commented
I feel  like I  should double check with @bpasquer  about this error.

I don't see any validation check left  about survey  block  methods. 
Maybe it's an issue where we have to retrieve this combo.

2021-04-22 01:30 UTC, ccmoloney commented
Is this error saying that you have a duplicate Method 2/Block 2 in the survey you are ingesting?

2021-04-22 01:39 UTC, utas-tajona commented
we are trying to add again the survey_method which shouldn't happen

2021-04-22 01:43 UTC, ccmoloney commented
"I feel like I should double check with @bpasquer about this error.

I don't see any validation check left about survey block methods.
Maybe it's an issue where we have to retrieve this combo."

Are we missing a check @utas-tajona ?

2021-04-22 01:54 UTC, utas-tajona commented
from https://github.com/aodn/backlog/issues/2933 and https://github.com/aodn/backlog/issues/2901 none of them as a check related to survey_id + method + block.

In the code we awlays are inserting the survey_id, method_id, block_id. which make sens. 
date / diver / site  + method + block should always be uniq

2021-04-22 01:55 UTC, utas-tajona commented
so we are clearly missing a check if the survey_method already exists

2021-04-22 02:30 UTC, utas-tajona commented
for the error message, the backendcurent implementation doesn't deal with error message. seems like another task to add

2021-04-22 02:55 UTC, nspool commented
OK, will evaluate this PR just based on a successful condition.

2021-04-22 03:09 UTC, ccmoloney commented
> from [aodn/backlog#2933](https://github.com/aodn/backlog/issues/2933) and [aodn/backlog#2901](https://github.com/aodn/backlog/issues/2901) none of them as a check related to survey_id + method + block.
> 
> In the code we awlays are inserting the survey_id, method_id, block_id. which make sens.
> date / diver / site + method + block should always be uniq

So: we are saying that we are not detecting duplicate blocks in the data for a new survey?

2021-04-22 03:22 UTC, utas-tajona commented
re deployed: http://nrmn-fixing-ingest.dev.aodn.org.au/home

2021-04-22 03:51 UTC, nspool commented
Created a new diver and site and made a new file with different dates. However still getting an error. File and logs from stack attached.

[TailLogs-1619063276401.txt](https://github.com/aodn/nrmn-application/files/6355379/TailLogs-1619063276401.txt)
[NATHAN TEST NEW SITE AND DIVER.xlsx](https://github.com/aodn/nrmn-application/files/6355380/NATHAN.TEST.NEW.SITE.AND.DIVER.xlsx)

2021-04-22 03:58 UTC, utas-tajona commented
your sheet is full of duplicates 

ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.2 | 1 | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.1 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.2 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.1 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.2 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.1 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.2 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.2 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.4 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.3 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.4 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.3 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.4 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.4 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.4 | 1 | 0
ger | NEWSITE | New Site | -42.72013855 | 148.011459351 | 2/02/2018 | 7 | N | 11:00:00 | 0 | 5.3 | 1 | 0

get-newsite-2022018-1-0 is duplicated more than 10 times

2021-04-22 05:16 UTC, nspool commented
@utas-tajona Tried again with a sheet with 3 lines but still seeing the internal server error. Which columns do I need to modify?

[NATHAN TEST NEW SITE AND DIVER SMALL.xlsx](https://github.com/aodn/nrmn-application/files/6355656/NATHAN.TEST.NEW.SITE.AND.DIVER.SMALL.xlsx)

2021-04-22 05:31 UTC, nspool commented
Log for previous error: 
[catalina.txt](https://github.com/aodn/nrmn-application/files/6355721/catalina.txt)

2021-04-22 05:46 UTC, utas-tajona commented
i managed to ingested it. Method 0 isn't supported in the current implementation. I will double check  with @bpasquer  when i can.

2021-04-23 02:24 UTC, ccmoloney commented
I think this can be merged to allow testing by Bene in edge.

The focus of that testing should be to identify if the current set of validation rules are verifying what they should be & whether or not datasheet we are indicating is valid is, in fact, able to be ingested correctly.

2021-04-23 02:52 UTC, nspool commented
@ccmoloney OK, will merge when checks are succeeding.

2021-04-23 04:16 UTC, merged