no species found
aodn/nrmn-application pull request #236
Opened 2021-04-27 06:42 UTC by utas-tajona

2021-04-27 06:48 UTC, utas-tajona commented
https://github.com/aodn/backlog/issues/2933

2021-04-28 00:30 UTC, jonescc commented on api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
> +                        Tuple2.of("found",new SpeciesNotFoundCheck()),
Need an import for this - getting a build error.

2021-04-28 00:31 UTC, jonescc requested changes
Looks good to me - but we need to fix that build error.

2021-04-29 01:12 UTC, jonescc approved these changes
Works OK for non-zero measures for species not found but doesn't check total/inverts as per spec.

Merging as the measure checks work and noting this on backlog item for @bpasquer to clarify.

2021-04-29 01:12 UTC, merged

2021-04-29 01:15 UTC, jonescc commented
Also I note that we get more than one species heading now - one for this check and one for Species not found checks.  Not sure if that's important.

2021-04-29 01:16 UTC, jonescc commented
![image](https://user-images.githubusercontent.com/1860215/116491038-43481100-a8dc-11eb-9d2c-76a6ed0f228a.png)