Uncommenting ui_species_attributes
aodn/nrmn-application pull request #276
Opened 2021-05-10 06:19 UTC by utas-tajona

2021-05-11 05:27 UTC, jonescc commented on api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
> +        val speciesAttributesOtp = obsRepo.getSpeciesAttributesById(new Long(species.getObservableItemId()));
Species can be null for "Survey not done" so this can result in a null pointer exception.

2021-05-11 05:34 UTC, utas-tajona commented
https://github.com/aodn/backlog/issues/2962

2021-05-12 02:54 UTC, jonescc commented on api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
> +        val speciesAttributesOtp = obsRepo.getSpeciesAttributesById(new Long(species.getObservableItemId()));
Optional<StagedRowFormatted>  is a much better way of handling that

2021-05-12 03:12 UTC, jonescc requested changes
Getting a null pointer exception trying to validate DuplicateSurvey (from edge)

2021-05-12 04:56 UTC, utas-tajona commented
That is a new bug discover nothing related to this change

2021-05-12 05:04 UTC, jonescc commented
> That is a new bug discover nothing related to this change

I only get the error on this branch.   I can't merge this until its fixed otherwise we'll break the new release.

2021-05-12 05:13 UTC, utas-tajona commented
it's probably already breaking on the current release. i changed the validator condition

2021-05-13 00:01 UTC, jonescc commented
Still getting a null pointer exception validating maria island.

```
2021-05-13 09:58:06.460 ERROR 13532 --- [io-8080-exec-10] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/api/stage/validate/33] due to exception [null]

java.lang.NullPointerException: null
	at au.org.aodn.nrmn.restapi.validation.validators.formatted.SpeciesAbundanceCheck.valid(SpeciesAbundanceCheck.java:24) ~[classes/:0.0.186]
	at au.org.aodn.nrmn.restapi.validation.process.FormattedValidation.lambda$null$0(FormattedValidation.java:61) ~[classes/:0.0.186]
	at cyclops.data.Seq$Cons.map(Seq.java:797) ~[cyclops-10.0.1.jar:10.0.1]
	at au.org.aodn.nrmn.restapi.validation.process.FormattedValidation.lambda$process$2(FormattedValidation.java:61) ~[classes/:0.0.186]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_292]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_292]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_292]
``

2021-05-13 00:03 UTC, jonescc commented
I think its due to this:

```
        if (target.getMethod() != 1 &&
                target.getMethod() != 2 &&
                !target.getSpeciesAttributesOpt().isPresent())
            return Validated.valid("No affected");

-->     val maxAbundance = target.getSpeciesAttributesOpt().get().getMaxAbundance();
```

The present check above is conditional meaning sometimes its not present when using the get()

2021-05-13 03:29 UTC, jonescc commented
Still getting null pointer exceptions - this time trying to perform l5/l95 checks:

```
2021-05-13 13:25:48.369 ERROR 48079 --- [nio-8080-exec-9] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/api/stage/validate/33] due to exception [null]

java.lang.NullPointerException: null
	at au.org.aodn.nrmn.restapi.validation.validators.formatted.MeasureBetweenL5l95.lambda$valid$0(MeasureBetweenL5l95.java:41) ~[classes/:0.0.186]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_292]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[na:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_292]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_292]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_292]
	at au.org.aodn.nrmn.restapi.validation.validators.formatted.MeasureBetweenL5l95.valid(MeasureBetweenL5l95.java:42) ~[classes/:0.0.186]
	at au.org.aodn.nrmn.restapi.validation.process.FormattedValidation.lambda$null$0(FormattedValidation.java:61) ~[classes/:0.0.186]
	at cyclops.data.Seq$Cons.map(Seq.java:797) ~[cyclops-10.0.1.jar:10.0.1]
	at au.org.aodn.nrmn.restapi.validation.process.FormattedValidation.lambda$process$2(FormattedValidation.java:61) ~[classes/:0.0.186]
```

2021-05-13 05:33 UTC, jonescc approved these changes

2021-05-13 05:33 UTC, merged